/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { ProjectCreateNestedManyWithoutPortfoliosInput } from "./ProjectCreateNestedManyWithoutPortfoliosInput";
import { Type } from "class-transformer";
import { SkillCreateNestedManyWithoutPortfoliosInput } from "./SkillCreateNestedManyWithoutPortfoliosInput";
import { TestimonialCreateNestedManyWithoutPortfoliosInput } from "./TestimonialCreateNestedManyWithoutPortfoliosInput";

@InputType()
class PortfolioCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactEmail?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  introduction?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ownerName?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProjectCreateNestedManyWithoutPortfoliosInput,
  })
  @ValidateNested()
  @Type(() => ProjectCreateNestedManyWithoutPortfoliosInput)
  @IsOptional()
  @Field(() => ProjectCreateNestedManyWithoutPortfoliosInput, {
    nullable: true,
  })
  projects?: ProjectCreateNestedManyWithoutPortfoliosInput;

  @ApiProperty({
    required: false,
    type: () => SkillCreateNestedManyWithoutPortfoliosInput,
  })
  @ValidateNested()
  @Type(() => SkillCreateNestedManyWithoutPortfoliosInput)
  @IsOptional()
  @Field(() => SkillCreateNestedManyWithoutPortfoliosInput, {
    nullable: true,
  })
  skills?: SkillCreateNestedManyWithoutPortfoliosInput;

  @ApiProperty({
    required: false,
    type: () => TestimonialCreateNestedManyWithoutPortfoliosInput,
  })
  @ValidateNested()
  @Type(() => TestimonialCreateNestedManyWithoutPortfoliosInput)
  @IsOptional()
  @Field(() => TestimonialCreateNestedManyWithoutPortfoliosInput, {
    nullable: true,
  })
  testimonials?: TestimonialCreateNestedManyWithoutPortfoliosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { PortfolioCreateInput as PortfolioCreateInput };
