/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Portfolio as PrismaPortfolio,
  Project as PrismaProject,
  Skill as PrismaSkill,
  Testimonial as PrismaTestimonial,
} from "@prisma/client";

export class PortfolioServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PortfolioCountArgs, "select">
  ): Promise<number> {
    return this.prisma.portfolio.count(args);
  }

  async portfolios(
    args: Prisma.PortfolioFindManyArgs
  ): Promise<PrismaPortfolio[]> {
    return this.prisma.portfolio.findMany(args);
  }
  async portfolio(
    args: Prisma.PortfolioFindUniqueArgs
  ): Promise<PrismaPortfolio | null> {
    return this.prisma.portfolio.findUnique(args);
  }
  async createPortfolio(
    args: Prisma.PortfolioCreateArgs
  ): Promise<PrismaPortfolio> {
    return this.prisma.portfolio.create(args);
  }
  async updatePortfolio(
    args: Prisma.PortfolioUpdateArgs
  ): Promise<PrismaPortfolio> {
    return this.prisma.portfolio.update(args);
  }
  async deletePortfolio(
    args: Prisma.PortfolioDeleteArgs
  ): Promise<PrismaPortfolio> {
    return this.prisma.portfolio.delete(args);
  }

  async findProjects(
    parentId: string,
    args: Prisma.ProjectFindManyArgs
  ): Promise<PrismaProject[]> {
    return this.prisma.portfolio
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .projects(args);
  }

  async findSkills(
    parentId: string,
    args: Prisma.SkillFindManyArgs
  ): Promise<PrismaSkill[]> {
    return this.prisma.portfolio
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .skills(args);
  }

  async findTestimonials(
    parentId: string,
    args: Prisma.TestimonialFindManyArgs
  ): Promise<PrismaTestimonial[]> {
    return this.prisma.portfolio
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .testimonials(args);
  }
}
