/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { ProjectUpdateManyWithoutPortfoliosInput } from "./ProjectUpdateManyWithoutPortfoliosInput";
import { Type } from "class-transformer";
import { SkillUpdateManyWithoutPortfoliosInput } from "./SkillUpdateManyWithoutPortfoliosInput";
import { TestimonialUpdateManyWithoutPortfoliosInput } from "./TestimonialUpdateManyWithoutPortfoliosInput";

@InputType()
class PortfolioUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactEmail?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  introduction?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ownerName?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProjectUpdateManyWithoutPortfoliosInput,
  })
  @ValidateNested()
  @Type(() => ProjectUpdateManyWithoutPortfoliosInput)
  @IsOptional()
  @Field(() => ProjectUpdateManyWithoutPortfoliosInput, {
    nullable: true,
  })
  projects?: ProjectUpdateManyWithoutPortfoliosInput;

  @ApiProperty({
    required: false,
    type: () => SkillUpdateManyWithoutPortfoliosInput,
  })
  @ValidateNested()
  @Type(() => SkillUpdateManyWithoutPortfoliosInput)
  @IsOptional()
  @Field(() => SkillUpdateManyWithoutPortfoliosInput, {
    nullable: true,
  })
  skills?: SkillUpdateManyWithoutPortfoliosInput;

  @ApiProperty({
    required: false,
    type: () => TestimonialUpdateManyWithoutPortfoliosInput,
  })
  @ValidateNested()
  @Type(() => TestimonialUpdateManyWithoutPortfoliosInput)
  @IsOptional()
  @Field(() => TestimonialUpdateManyWithoutPortfoliosInput, {
    nullable: true,
  })
  testimonials?: TestimonialUpdateManyWithoutPortfoliosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { PortfolioUpdateInput as PortfolioUpdateInput };
