/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { VitalSignsFindManyArgs } from "../../vitalSigns/base/VitalSignsFindManyArgs";
import { VitalSigns } from "../../vitalSigns/base/VitalSigns";
import { VitalSignsWhereUniqueInput } from "../../vitalSigns/base/VitalSignsWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        age: true,
        createdAt: true,
        email: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,
        name: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        age: true,
        createdAt: true,
        email: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,
        name: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        age: true,
        createdAt: true,
        email: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,
        name: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          age: true,
          createdAt: true,
          email: true,
          firstName: true,
          gender: true,
          id: true,
          lastName: true,
          name: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          age: true,
          createdAt: true,
          email: true,
          firstName: true,
          gender: true,
          id: true,
          lastName: true,
          name: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/vitalSignsItems")
  @ApiNestedQuery(VitalSignsFindManyArgs)
  async findVitalSignsItems(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<VitalSigns[]> {
    const query = plainToClass(VitalSignsFindManyArgs, request.query);
    const results = await this.service.findVitalSignsItems(params.id, {
      ...query,
      select: {
        bloodPressure: true,
        createdAt: true,
        heartAge: true,
        heartRate: true,
        heartRateVariability: true,
        id: true,
        respirationRate: true,
        spO2: true,
        timestamp: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/vitalSignsItems")
  async connectVitalSignsItems(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: VitalSignsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vitalSignsItems: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/vitalSignsItems")
  async updateVitalSignsItems(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: VitalSignsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vitalSignsItems: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/vitalSignsItems")
  async disconnectVitalSignsItems(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: VitalSignsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      vitalSignsItems: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
