/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Testimonial } from "./Testimonial";
import { TestimonialCountArgs } from "./TestimonialCountArgs";
import { TestimonialFindManyArgs } from "./TestimonialFindManyArgs";
import { TestimonialFindUniqueArgs } from "./TestimonialFindUniqueArgs";
import { CreateTestimonialArgs } from "./CreateTestimonialArgs";
import { UpdateTestimonialArgs } from "./UpdateTestimonialArgs";
import { DeleteTestimonialArgs } from "./DeleteTestimonialArgs";
import { Portfolio } from "../../portfolio/base/Portfolio";
import { TestimonialService } from "../testimonial.service";
@graphql.Resolver(() => Testimonial)
export class TestimonialResolverBase {
  constructor(protected readonly service: TestimonialService) {}

  async _testimonialsMeta(
    @graphql.Args() args: TestimonialCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Testimonial])
  async testimonials(
    @graphql.Args() args: TestimonialFindManyArgs
  ): Promise<Testimonial[]> {
    return this.service.testimonials(args);
  }

  @graphql.Query(() => Testimonial, { nullable: true })
  async testimonial(
    @graphql.Args() args: TestimonialFindUniqueArgs
  ): Promise<Testimonial | null> {
    const result = await this.service.testimonial(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Testimonial)
  async createTestimonial(
    @graphql.Args() args: CreateTestimonialArgs
  ): Promise<Testimonial> {
    return await this.service.createTestimonial({
      ...args,
      data: {
        ...args.data,

        portfolio: args.data.portfolio
          ? {
              connect: args.data.portfolio,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Testimonial)
  async updateTestimonial(
    @graphql.Args() args: UpdateTestimonialArgs
  ): Promise<Testimonial | null> {
    try {
      return await this.service.updateTestimonial({
        ...args,
        data: {
          ...args.data,

          portfolio: args.data.portfolio
            ? {
                connect: args.data.portfolio,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Testimonial)
  async deleteTestimonial(
    @graphql.Args() args: DeleteTestimonialArgs
  ): Promise<Testimonial | null> {
    try {
      return await this.service.deleteTestimonial(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Portfolio, {
    nullable: true,
    name: "portfolio",
  })
  async getPortfolio(
    @graphql.Parent() parent: Testimonial
  ): Promise<Portfolio | null> {
    const result = await this.service.getPortfolio(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
